### ISSUE TITLE
[New Feature Request] Adding names with Length widget

### ISSUE THREAD

**Issue by darjusp** [axanthos/TextablePrototypes#21]
**Textable version 3.0.7**
**Orange version 3.7.0**

Hi Aris, 

I tried to accomplish a task of calculating lengths of different segments, then merging them to an Orange table for further analysis, but then all output variables has same name (__length__). Please see pictures attached. It would good it there would be possibility for separately naming output variable in the Length widget, or if it would done automatically by input (Segment 1) or by number (__length1__, __length2__).
![screen shot 2017-11-14 at 18 21 21](https://user-images.githubusercontent.com/10597360/32791330-73c8965c-c969-11e7-8faf-a82a0ef1e92f.png)
![screen shot 2017-11-14 at 18 19 26](https://user-images.githubusercontent.com/10597360/32791355-7d47340e-c969-11e7-8eff-15d236898fd2.png)

**Comment by axanthos** [comment]
Hi Darjus, 
Thanks for your input and sorry for getting back to you so late.
I find your idea interesting but it's not as trivial to implement as it might seem and the problem you describe can be solved by using Orange's Edit Domain widget. 
I'll leave this issue open for now, however, as this is something I might implement in the future.
Btw this should be filed in the Textable repo rather than in Textable-Prototypes.

**Comment by darjusp** [comment]
Thanks Ari, sorry for mistake, and definitely will look into Edit Domain widget.
